name: Dependencies

description: Installs required dependencies

runs:
    using: composite
    steps:
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
              cache: "yarn"
              cache-dependency-path: yarn.lock
        - name: Install dependencies
          shell: bash
          run: yarn
