name: Blank

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get Number of Files Changed in src
        run: |
          git diff --name-only HEAD^ HEAD
          echo "NUMBER_OF_FILES_CHANGED=$(git diff --name-only | grep -c src)" >> $GITHUB_ENV

      - name: Print Number of Files Changed
        run: echo $NUMBER_OF_FILES_CHANGED
