name: CI

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  cache: "yarn"
                  cache-dependency-path: yarn.lock
            - name: Install dependencies
              run: yarn
            - name: Run Script
              run: yarn start
