name: CI

on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache dependencies
              id: node-cache
              uses: ./.github/actions/cache
            - name: Install dependencies
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: yarn && cd other && yarn
            - name: Typescript check
              run: yarn tsc
            - name: Linting
              run: yarn lint
    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cache dependencies
              id: cache
              uses: ./.github/actions/cache
            - name: Install dependencies
              if: steps.cache.outputs.node-cache-hit != 'true'
              run: yarn
            - name: Run Script
              run: yarn start
            - name: Install dependencies for App
              if: steps.cache.outputs.node-cache-hit != 'true'
              run: cd other && yarn
            - name: Build App
              if: steps.cache.outputs.build-cache-hit != 'true'
              run: cd other && yarn build
