name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    strategy:
      fail-fast: true
      matrix:
        task: [install, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: ./.github/actions/cache
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn && cd other && yarn
      - name: Typescript check
        if: matrix.task == 'install'
        run: yarn tsc
      - name: Linting
        if: matrix.task == 'install'
        run: yarn lint
      - name: Run Script
        if: matrix.task == 'build'
        run: yarn start
